### ISSUE TITLE
Form Helper: control-label not being applied and text may not be set

### ISSUE THREAD

**Issue by sams** [slywalker/TwitterBootstrap#19]
1) Control -Label class should be applied to label
https://github.com/slywalker/TwitterBootstrap/blob/master/View/Helper/BootstrapFormHelper.php#L20

`
 'label' => array('class' => 'control-label'),

`

2) $text may not be set
https://github.com/slywalker/TwitterBootstrap/blob/master/View/Helper/BootstrapFormHelper.php#L160

`
 $text = null;
 if(!empty($options['label']['text']))$text = $options['label']['text'];

`

all is is well afterwards

**Comment by slywalker** [comment]
It fixed 1.1.0.
