### ISSUE TITLE
Don't output HTML for hidden inputs

### ISSUE THREAD

**Issue by jmillerdesign** [slywalker/TwitterBootstrap#23]
For hidden inputs, such as the primary key on an edit action `echo $this->Form->input('id');` the plugin currently adds the label as well as `control-group` and `controls` divs. Ideally, the plugin should ignore this field and output the default FormHelper HTML, since it is simply a hidden input with no extra div markup.

**Comment by jmillerdesign** [comment]
`echo $this->Form->input('id', array('label' => false, 'div' => false));` works, but is not necessary normally, so would be extra options required to get this to work in the plugin.

**Comment by slywalker** [comment]
fixed v1.1.8

**Comment by jmillerdesign** [comment]
Should this be adjusted to also work if you set `'type' => 'hidden'`, in addition to the primaryKey?

**Comment by slywalker** [comment]
if id is primaryKey, 'type' => 'hidden' add automatically.

**Comment by jmillerdesign** [comment]
I'm proposing that if you add an input field that is not the primary key, and add `'type' => 'hidden'` then it should add `'div' => false, 'label' => false` to that field as well.

For example, if I add `$this->Form->input('name', array('type' => 'hidden'));`, then it makes sense to hide the label and div also.

**Comment by slywalker** [comment]
Oh! I see. I will fix it.

**Comment by slywalker** [comment]
Fixed v1.1.10

**Comment by jmillerdesign** [comment]
Thanks! Great plugin!
