### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by trante** [slywalker/TwitterBootstrap#28]
Thank you for these project!

Regarding to "This v1.1.10 supports Bootstrap v2.0.2"
Does v1.1.10 includes all bootstrap features or are there any missing ones that are planned to be integrated later?

thanks

**Comment by slywalker** [comment]
There was 3 big problem when using Bootstrap in CakePHP. Form, Pagination and Session::flush.
This plugin is their solution.

I think that Do not need support problem can be solved easily by the description of the HTML.
But, I think those future useful if there is going to add.

thanks
