### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by trante** [slywalker/TwitterBootstrap#29]
Hello,
Can you explain this text in installation ?
- Which part will we write? First $helpers array or second $helpers array?
- Where will we write these "public $helpers definition"? To AppController.php or to our derived Controller (example MyController.php) ? If we define them in "AppController.php" is it enough?
- Shouldn't we write this to our controller action?
  CakePlugin::load('TwitterBootstrap')

Thank you

```
// Usig as plugin's helper
public $helpers = array(
    'Session', 'Html', 'Form',
    'TwitterBootstrap.BootstrapHtml',
    'TwitterBootstrap.BootstrapForm',
    'TwitterBootstrap.BootstrapPaginator',
);

// Using as alias of core helper
public $helpers = array(
    'Session',
    'Html' => array('className' => 'TwitterBootstrap.BootstrapHtml'),
    'Form' => array('className' => 'TwitterBootstrap.BootstrapForm'),
    'Paginator' => array('className' => 'TwitterBootstrap.BootstrapPaginator'),
);
```

**Comment by slywalker** [comment]
Hi

I recommend that "Using as alias of core helper" in "AppController.php".

**Comment by trante** [comment]
Thank you @slywalker 
- So using "alias of core helper" suppresses the core "Html" helper ? That's cool then.

**Comment by slywalker** [comment]
Descriptive commentary is written to Cookbook.
[Welcome — Cookbook v2.x documentation](http://book.cakephp.org/2.0/en/)

[Using and Configuring Helpers](http://book.cakephp.org/2.0/en/views/helpers.html#using-and-configuring-helpers)

> One common setting to use is the className option, which allows you to create aliased helpers in your views. This feature is useful when you want to replace $this->Html or another common Helper reference with a custom implementation:

[Installing a Plugin](http://book.cakephp.org/2.0/en/plugins.html#installing-a-plugin)

> New for CakePHP 2.0, plugins need to be loaded manually in app/Config/bootstrap.php.
> You can either load them one by one or all of them in a single call:

**Comment by trante** [comment]
That would be helpful to add <a href="http://book.cakephp.org/2.0/en/plugins.html#installing-a-plugin">link</a>.
You know..
Thank you
