### ISSUE TITLE
bootstrap js plugin snippets

### ISSUE THREAD

**Issue by dereuromark** [slywalker/TwitterBootstrap#32]
I wrote a pretty basic js plugin snippet helper.
https://github.com/dereuromark/tools/blob/2.0/View/Helper/BootstrapHelper.php

in case you plan on including some of it in your rep.
we could probably make it elements, too.
but my idea was that it takes care of including js and other things automatically as well.

**Comment by slywalker** [comment]
Hi.
Good Helper!

I think more better that helper extends JsHelper, and BootstrapJsHelper use as alias JsHelper.
Please, fork my repository, and pull request that helper.

**Comment by justinledwards** [comment]
I really like this guy's datepicker.  http://dl.dropbox.com/u/143355/datepicker/datepicker.html  It would be good to incorporate.

**Comment by slywalker** [comment]
Development of this plugin has moved [here](https://github.com/slywalker/cakephp-plugin-boost_cake).
