### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by richardwo** [slywalker/TwitterBootstrap#35]
Query on installation instructions.
When I follow this instruction:
View/Layout/default.ctp
    <?php echo $this->Html->css('bootstrap.min'); ?>
    <?php echo $this->Html->css('bootstrap-responsive.min'); ?>

CakePHP generates this in my HTML

``` HTML
<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="/css/bootstrap-responsive.min.css" />
```

but these files don't exist, the instructions told us to put them in app/Plugin/TwitterBootstrap/webroot
Should it look like this?
<?php echo $this->Html->css('/twitter_bootstrap/css/bootstrap.min'); ?>
<?php echo $this->Html->css('/twitter_bootstrap/css/bootstrap-responsive.min'); ?>

Same thing for the <?php echo $this->Html->script('bootstrap.min'); ?>

**Comment by slywalker** [comment]
Did you install download or clone?

If you downloaded install, you have to download files from Bootstrap Site, and move files /your_app/webroot.

**Comment by richardwo** [comment]
I downloaded.

Thanks - that's fine, will move my files.
Installation instructions currently say "move files to app/Plugin/TwitterBootstrap/webroot/" - you might want to change that.

**Comment by slywalker** [comment]
Yes

if you move files to app/Plugin/TwitterBootstrap/webroot/

<?php echo $this->Html->css('/twitter_bootstrap/css/bootstrap.min'); ?>
<?php echo $this->Html->css('/twitter_bootstrap/css/bootstrap-responsive.min'); ?>
<?php echo $this->Html->script('/twitter_bootstrap/js/bootstrap.min'); ?>

[Linking to assets in plugins](http://book.cakephp.org/2.0/en/plugins.html#linking-to-assets-in-plugins)
