### ISSUE TITLE
Support for grid based forms

### ISSUE THREAD

**Issue by CauanCabral** [slywalker/TwitterBootstrap#37]
Hi,

I've work in add support of grid based forms and the results are here: https://github.com/radig/TwitterBootstrap

Any interest merge it?

**Comment by justinledwards** [comment]
Have a link to it in use?

**Comment by CauanCabral** [comment]
Sure: http://comitiva.phpms.org/account_create
Source: https://github.com/CauanCabral/Comitiva/blob/2.0/View/Users/account_create.ctp

**Comment by CauanCabral** [comment]
I've included some fixes for grid support and other 'enchancements':
- Using input type text for date/timestamp fields
- Re-enabled labels for checkbox input types
- Using input type text for float because of incosistency in treatment of decimal point on differents browsers
- Support for glyph icons (font-based icons) wich depends on FontAwesome - http://fortawesome.github.com/Font-Awesome/
- Correctly setting 'required' class at 'div' element of required inputs

**Comment by gnumoksha** [comment]
Any interest merge it?

**Comment by slywalker** [comment]
Development of this plugin has moved [here](https://github.com/slywalker/cakephp-plugin-boost_cake).
