### ISSUE TITLE
Pagination in index action doesn't work in a scaffolded controller

### ISSUE THREAD

**Issue by ravage84** [slywalker/TwitterBootstrap#52]
If you bake a controller and choose to scaffold it instead of baking the views too, then the pagination will be broken because the the template for scaffolding \lib\Cake\View\Scaffolds\index.ctp generatates the pagination differently than the \app\Plugin\TwitterBootstrap\Console\Templates\bootstrap\views\index.ctp does.

This issue is not really important but it would be may be wise to outline it in the docs to prevent further issue reports about this.
I guess a simple "Don't use scaffolding with this plugin, because of..." or something like this would do.

**Comment by slywalker** [comment]
Development of this plugin has moved [here](https://github.com/slywalker/cakephp-plugin-boost_cake).
