### ISSUE TITLE
Submodule clone failure

### ISSUE THREAD

**Issue by jlpuder** [slywalker/TwitterBootstrap#71]
With the development of Bootstrap 3, Twitter has deleted the Bootstrap 2 repo and thus doing
`git submodule update --init`
after the main repo clone fails. All that really needs to be done is to change the installation instructions to manually include the upload, or include the files in the repo. I just wanted to bring it to your attention and you can address it how you see best fit.

**Comment by slywalker** [comment]
Development of this plugin has moved [BoostCake](https://github.com/slywalker/cakephp-plugin-boost_cake).
