### ISSUE TITLE
Update to function with Twitter Bootstrap v3.0?

### ISSUE THREAD

**Issue by thomasvnl** [slywalker/TwitterBootstrap#72]
Hi Slywalker,

Are you by any chance planning on updating your CakePHP Plugin to function with Twitter Bootstrap V3.0, the latest iteration by @mdo and @fat? 

If not, I will try to update/convert your code myself so it will function properly, but with you being the author I just wanted to ask if you weren't working on such a thing already.

Regards,
Thomas

**Comment by slywalker** [comment]
Development of this plugin has moved [BoostCake](https://github.com/slywalker/cakephp-plugin-boost_cake).
BoostCake supports Bootstrap v3.0 and was fixed TwitterBootstrap's bugs.

**Comment by thomasvnl** [comment]
Nice! Thanks @slywalker
